#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  bootstrap_machine.sh [--role presentation|relay-agent|controller|all] [--install-hotkey]

Roles:
  presentation  Create config/local.env if missing and prep local runner.
  relay-agent   Create config/relay_agent.env if missing.
  controller    Create controller trigger configs if missing.
  all           Prepare all local config files (default).

Hotkey options:
  --install-hotkey          Install/configure Hammerspoon hotkey integration.
  --hotkey-mode MODE        local|relay|ssh (default: local)
  --hotkey-config PATH      Config file path for selected mode (default based on mode)
  --hotkey-mods CSV         Hotkey modifiers (default: ctrl,alt,cmd)
  --hotkey-key KEY          Hotkey key (default: r)
USAGE
}

ROLE="all"
INSTALL_HOTKEY=0
HOTKEY_MODE="local"
HOTKEY_CONFIG=""
HOTKEY_MODS_CSV="ctrl,alt,cmd"
HOTKEY_KEY="r"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --role)
      ROLE="${2:-}"
      shift 2
      ;;
    --install-hotkey)
      INSTALL_HOTKEY=1
      shift 1
      ;;
    --hotkey-mode)
      HOTKEY_MODE="${2:-}"
      shift 2
      ;;
    --hotkey-config)
      HOTKEY_CONFIG="${2:-}"
      shift 2
      ;;
    --hotkey-mods)
      HOTKEY_MODS_CSV="${2:-}"
      shift 2
      ;;
    --hotkey-key)
      HOTKEY_KEY="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$PROJECT_ROOT/config"
HOME_HAMMERSPOON_DIR="$HOME/.hammerspoon"

lua_escape() {
  local input="$1"
  input="${input//\\/\\\\}"
  input="${input//\"/\\\"}"
  printf '%s' "$input"
}

setup_hammerspoon_hotkey() {
  local hotkey_config_path
  local project_root_lua
  local trigger_config_lua
  local init_file
  local hook_line
  local lua_mods
  local old_ifs
  local one_mod

  case "$HOTKEY_MODE" in
    local)
      hotkey_config_path="$PROJECT_ROOT/config/local.env"
      ;;
    relay)
      hotkey_config_path="$PROJECT_ROOT/config/relay_streamdeck.env"
      ;;
    ssh)
      hotkey_config_path="$PROJECT_ROOT/config/controller.env"
      ;;
    *)
      echo "Invalid --hotkey-mode: $HOTKEY_MODE (expected: local, relay, ssh)" >&2
      exit 1
      ;;
  esac

  if [[ -n "$HOTKEY_CONFIG" ]]; then
    hotkey_config_path="$HOTKEY_CONFIG"
  fi

  if [[ ! -d /Applications/Hammerspoon.app ]]; then
    if ! command -v brew >/dev/null 2>&1; then
      echo "Homebrew not found. Install Homebrew first, then rerun with --install-hotkey." >&2
      exit 1
    fi

    echo "Installing Hammerspoon..."
    brew install --cask hammerspoon
  fi

  mkdir -p "$HOME_HAMMERSPOON_DIR"

  project_root_lua="$(lua_escape "$PROJECT_ROOT")"
  trigger_config_lua="$(lua_escape "$hotkey_config_path")"

  lua_mods=""
  old_ifs="$IFS"
  IFS=','
  for one_mod in $HOTKEY_MODS_CSV; do
    one_mod="${one_mod#"${one_mod%%[![:space:]]*}"}"
    one_mod="${one_mod%"${one_mod##*[![:space:]]}"}"
    if [[ -n "$one_mod" ]]; then
      if [[ -n "$lua_mods" ]]; then
        lua_mods+=", "
      fi
      lua_mods+="\"$one_mod\""
    fi
  done
  IFS="$old_ifs"

  if [[ -z "$lua_mods" ]]; then
    lua_mods="\"ctrl\", \"alt\", \"cmd\""
  fi

  cat > "$HOME_HAMMERSPOON_DIR/slides_hotkey.lua" <<EOF
-- Auto-generated by scripts/bootstrap_machine.sh
local projectRoot = "$project_root_lua"
local triggerScript = projectRoot .. "/scripts/slides_hotkey_trigger.sh"
local triggerMode = "$HOTKEY_MODE"
local triggerConfig = "$trigger_config_lua"
local hotkeyMods = {$lua_mods}
local hotkeyKey = "$HOTKEY_KEY"

local function runSlidesTrigger()
  local args = {"--mode", triggerMode, "--config", triggerConfig}

  local task = hs.task.new(triggerScript, function(exitCode, stdOut, stdErr)
    if exitCode == 0 then
      hs.notify.new({ title = "Slides", informativeText = "Refresh triggered" }):send()
    else
      hs.notify.new({ title = "Slides", informativeText = "Refresh failed (" .. tostring(exitCode) .. ")" }):send()
    end

    if stdOut and #stdOut > 0 then print(stdOut) end
    if stdErr and #stdErr > 0 then print(stdErr) end
    return true
  end, args)

  if task then
    task:start()
  else
    hs.notify.new({ title = "Slides", informativeText = "Failed to create hotkey task" }):send()
  end
end

hs.hotkey.bind(hotkeyMods, hotkeyKey, runSlidesTrigger)
print("Slides hotkey ready: " .. table.concat(hotkeyMods, "+") .. "+" .. string.upper(hotkeyKey))
EOF

  init_file="$HOME_HAMMERSPOON_DIR/init.lua"
  hook_line='dofile(os.getenv("HOME") .. "/.hammerspoon/slides_hotkey.lua")'

  if [[ -f "$init_file" ]]; then
    if ! grep -Fq "$hook_line" "$init_file"; then
      {
        echo ""
        echo "-- Slides hotkey integration"
        echo "$hook_line"
      } >> "$init_file"
    fi
  else
    cat > "$init_file" <<EOF
-- Hammerspoon init created by bootstrap_machine.sh
$hook_line
EOF
  fi

  open -a Hammerspoon
  sleep 1
  if command -v hs >/dev/null 2>&1; then
    hs -c 'hs.reload()' >/dev/null 2>&1 || true
  fi

  echo "Hotkey setup complete."
  echo "Configured: $HOME_HAMMERSPOON_DIR/slides_hotkey.lua"
  echo "Hotkey: $HOTKEY_MODS_CSV+$HOTKEY_KEY"
  echo "Mode/config: $HOTKEY_MODE -> $hotkey_config_path"
  echo "If hotkey still does nothing, enable Accessibility for Hammerspoon:"
  echo "System Settings -> Privacy & Security -> Accessibility -> Hammerspoon"
}

create_if_missing() {
  local src="$1"
  local dst="$2"

  if [[ ! -f "$dst" ]]; then
    cp "$src" "$dst"
    echo "Created: $dst"
  else
    echo "Exists:  $dst"
  fi
}

chmod +x "$PROJECT_ROOT"/scripts/*.sh

echo "Bootstrap role: $ROLE"

case "$ROLE" in
  presentation)
    create_if_missing "$CONFIG_DIR/local.env.example" "$CONFIG_DIR/local.env"
    ;;
  relay-agent)
    create_if_missing "$CONFIG_DIR/local.env.example" "$CONFIG_DIR/local.env"
    create_if_missing "$CONFIG_DIR/relay_agent.env.example" "$CONFIG_DIR/relay_agent.env"
    ;;
  controller)
    create_if_missing "$CONFIG_DIR/relay_streamdeck.env.example" "$CONFIG_DIR/relay_streamdeck.env"
    create_if_missing "$CONFIG_DIR/controller.env.example" "$CONFIG_DIR/controller.env"
    ;;
  all)
    create_if_missing "$CONFIG_DIR/local.env.example" "$CONFIG_DIR/local.env"
    create_if_missing "$CONFIG_DIR/relay_agent.env.example" "$CONFIG_DIR/relay_agent.env"
    create_if_missing "$CONFIG_DIR/relay_streamdeck.env.example" "$CONFIG_DIR/relay_streamdeck.env"
    create_if_missing "$CONFIG_DIR/controller.env.example" "$CONFIG_DIR/controller.env"
    ;;
  *)
    echo "Invalid role: $ROLE" >&2
    exit 1
    ;;
esac

if [[ "$INSTALL_HOTKEY" == "1" ]]; then
  setup_hammerspoon_hotkey
fi

echo "Done. Next: edit config files for this machine, then run the matching script from README/DEPLOY.md."
